modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "more_quest_types"
version = "${version}"
displayName = "More Quest Types"
authors = "KevzCz"
description = '''
Add new tasks and rewards to ftbquests!
'''
logoFile = "assets/more_quest_types/icon.png"

[[dependencies.more_quest_types]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.more_quest_types]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.more_quest_types]]
modId = "ftbquests"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.more_quest_types]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "more_quest_types.mixins.json"
side = "BOTH"

[[mixins]]
config = "more_quest_types.neoforge.mixins.json"
side = "BOTH"